-- =============================================================================
-- FILE: 01_core_tables.sql
-- PURPOSE: Foundation tables — apartments, invites, users, roles, and profiles.
--          Everything else in the schema depends on these.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- APARTMENTS
-- Represents a residential complex or gated community. The entire platform
-- is scoped to one or more apartments. Each apartment is a trust boundary.
-- ---------------------------------------------------------------------------
CREATE TABLE apartments (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    name                TEXT            NOT NULL,                     -- e.g. "Prestige Lakeside Habitat"
    address_line1       TEXT            NOT NULL,
    address_line2       TEXT,
    city                TEXT            NOT NULL,
    state               TEXT            NOT NULL,
    country             TEXT            NOT NULL DEFAULT 'India',
    postal_code         TEXT            NOT NULL,
    total_units         INTEGER,                                      -- Informational; helps capacity planning
    admin_contact_email TEXT,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE apartments IS
    'Each row is a residential community. The platform may host multiple apartments.';

-- ---------------------------------------------------------------------------
-- APARTMENT_INVITES
-- Controls who is allowed to join. An admin generates an invite (email + token).
-- The token is emailed to the resident; they must use it to register.
-- Prevents open public registration.
-- ---------------------------------------------------------------------------
CREATE TABLE apartment_invites (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    apartment_id    UUID            NOT NULL REFERENCES apartments(id) ON DELETE CASCADE,
    invited_email   TEXT            NOT NULL,
    token           TEXT            NOT NULL UNIQUE,                  -- Cryptographically random, hashed in app layer
    token_expires_at TIMESTAMPTZ    NOT NULL,                         -- Short-lived (48–72 hrs typical)
    unit_number     TEXT,                                             -- Optional: flat/unit number for pre-filling
    status          invite_status   NOT NULL DEFAULT 'pending',
    invited_by      UUID,                                             -- FK to users(id) added after users table exists
    used_by         UUID,                                             -- FK set when user registers with this token
    notes           TEXT,                                             -- Admin notes (e.g. "Owner of unit 4B")
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT invite_email_format CHECK (invited_email ~* '^[^@]+@[^@]+\.[^@]+$')
);

CREATE INDEX idx_apartment_invites_apartment ON apartment_invites(apartment_id);
CREATE INDEX idx_apartment_invites_token     ON apartment_invites(token);
CREATE INDEX idx_apartment_invites_email     ON apartment_invites(invited_email);
CREATE INDEX idx_apartment_invites_status    ON apartment_invites(status);

COMMENT ON TABLE apartment_invites IS
    'Invite tokens generated by admins to allow specific residents to register.
     Prevents open public signups.';

-- ---------------------------------------------------------------------------
-- USERS
-- Core auth entity. Intentionally kept thin — rich profile data lives in
-- user_profiles. Auth (password hash, OAuth tokens) is handled by the
-- application layer / Supabase Auth; we store only the reference ID.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_uid            UUID            UNIQUE,                       -- Maps to Supabase auth.users.id or equivalent
    email               TEXT            NOT NULL UNIQUE,
    phone               TEXT            UNIQUE,
    apartment_id        UUID            NOT NULL REFERENCES apartments(id),
    unit_number         TEXT,                                         -- Resident's flat number
    invite_id           UUID            REFERENCES apartment_invites(id),
    status              user_status     NOT NULL DEFAULT 'pending',
    email_verified      BOOLEAN         NOT NULL DEFAULT FALSE,
    phone_verified      BOOLEAN         NOT NULL DEFAULT FALSE,
    last_login_at       TIMESTAMPTZ,
    deleted_at          TIMESTAMPTZ,                                  -- Soft delete
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT users_email_format CHECK (email ~* '^[^@]+@[^@]+\.[^@]+$')
);

-- Backfill FK from apartment_invites now that users exists
ALTER TABLE apartment_invites
    ADD CONSTRAINT fk_invite_invited_by FOREIGN KEY (invited_by) REFERENCES users(id),
    ADD CONSTRAINT fk_invite_used_by    FOREIGN KEY (used_by)    REFERENCES users(id);

CREATE INDEX idx_users_apartment       ON users(apartment_id);
CREATE INDEX idx_users_status          ON users(status);
CREATE INDEX idx_users_email           ON users(email);
CREATE INDEX idx_users_auth_uid        ON users(auth_uid);
CREATE INDEX idx_users_deleted_at      ON users(deleted_at) WHERE deleted_at IS NULL;

COMMENT ON TABLE users IS
    'Core account entity. Restricted to verified apartment residents.
     Auth credentials live in the auth provider (e.g. Supabase). 
     deleted_at IS NULL = active account.';

-- ---------------------------------------------------------------------------
-- USER_ROLES
-- Many-to-many: a user can be a learner AND a provider AND an admin.
-- Roles are granted/revoked explicitly rather than stored as an array,
-- making permission checks and auditing cleaner.
-- ---------------------------------------------------------------------------
CREATE TABLE user_roles (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role        user_role   NOT NULL,
    granted_by  UUID        REFERENCES users(id),                     -- Admin who granted the role
    granted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at  TIMESTAMPTZ,                                          -- NULL means currently active

    CONSTRAINT uq_user_role UNIQUE (user_id, role)
);

CREATE INDEX idx_user_roles_user ON user_roles(user_id);
CREATE INDEX idx_user_roles_role ON user_roles(role);

COMMENT ON TABLE user_roles IS
    'Explicit role assignments. A user can hold multiple roles simultaneously.
     Revoked roles are kept for audit history.';

-- ---------------------------------------------------------------------------
-- USER_PROFILES
-- Extended profile info: display name, bio, avatar, social links, etc.
-- 1:1 with users. Separated so the users table stays focused on auth/status.
-- ---------------------------------------------------------------------------
CREATE TABLE user_profiles (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    display_name    TEXT        NOT NULL,
    avatar_url      TEXT,
    bio             TEXT,
    languages       TEXT[],                                           -- e.g. ARRAY['English', 'Hindi']
    skills_offered  TEXT[],                                           -- Free-text tags, indexed listing managed in listings
    interests       TEXT[],
    website_url     TEXT,
    linkedin_url    TEXT,
    is_public       BOOLEAN     NOT NULL DEFAULT TRUE,                -- Can learners see full profile?
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_profiles_user ON user_profiles(user_id);

COMMENT ON TABLE user_profiles IS
    'Rich profile data for display in the community directory and provider pages.
     1:1 extension of the users table.';
